export const Data = [
    {
        id:1,
        image:"./MATW Orphans.jpeg",
        title:"MATW Orphans Campaign",
        description:"Become a Guardian of Orphans around the world with MATW(Muslims Around The World).",
        link:"https://www.launchgood.com/v4/campaign/matw_orphans_campaign?src=3520781",
        value:"1,283",
    },
    {
        id:2,
        image:"./SNGC.jpg",
        title:"Provide Aid to Gaza & Syria.",
        description:"Spread your rewards and be part of 12 projects in one, supporting both Syria and Gaza!",
        link:"https://www.launchgood.com/v4/campaign/donate_to_provide_aid_to_the_people_of_gaza__syria?src=3520781",
        value:"1,283",
    },
    {
        id:3,
        image:"./WCHC.jpeg",
        title:"Mother and Child Health.",
        description:"Help us bring free Healthcare to Women and Children in Pakistan.",
        link:"https://www.launchgood.com/v4/campaign/international_foundation_for_mother_and_child_health?src=3520781",
        value:"1,283",
    },
    // {
    //     id:4,
    //     image:"./wallpaper5.jfif",
    //     title:"Donation Title Here",
    //     description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo eius consequatur nam, voluptatum exercitationem velit nemo dolorum amet,",
    //     value:"500",
    // },
    // {
    //     id:5,
    //     image:"./wallpaper5.jfif",
    //     title:"Donation Title Here",
    //     description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo eius consequatur nam, voluptatum exercitationem velit nemo dolorum amet,",
    //     value:"500",
    // },
    // {
    //     id:6,
    //     image:"./wallpaper5.jfif",
    //     title:"Donation Title Here",
    //     description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo eius consequatur nam, voluptatum exercitationem velit nemo dolorum amet,",
    //     value:"500",
    // },
    // {
    //     id:7,
    //     image:"./wallpaper5.jfif",
    //     title:"Donation Title Here",
    //     description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo eius consequatur nam, voluptatum exercitationem velit nemo dolorum amet,",
    //     value:"500",
    // },
]
